version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - lets-do-it-together

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    networks:
      - lets-do-it-together

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST}
    env_file:
      - .env
    networks:
      - lets-do-it-together

  auth-service:
    build:
      context: ./auth-service
      target: prod
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
      - mongo-express
    ports:
      - "8090:8090"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE: ${DATABASE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AUTH_DATABASE: ${AUTH_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    env_file:
      - .env
    networks:
      - lets-do-it-together

networks:
  lets-do-it-together:
    external: true